### ISSUE TITLE
Error 502 Bad Gateway when deploying into ACI

### ISSUE THREAD

**Issue by ChRocheFR** [Azure-Samples/azure-voting-app-redis#43]
I followed the tutorial for deploying this app in Azure Container Registry but tried to launch the app with Azure Container Instance (with a Linux machine). The deployment went well but when reaching the site, I got a 502 error.

Do not really know if I made a mistake or if this is due to the code itself.

**Comment by jeanjluo** [comment]
Try changing the port in docker-compose.yaml from 8080 to 80:

```
version: '3'
services:
  azure-vote-back:
    image: redis
    container_name: azure-vote-back
    ports:
        - "6379:6379"

  azure-vote-front:
    build: ./azure-vote
    image: azure-vote-front
    container_name: azure-vote-front
    environment:
      REDIS: azure-vote-back
    ports:
        - "80:80"
```
